baseURL = "https://singleservingphoto.com"
languageCode = "en-us"
title = "Single-Serving Photo"
theme = "ssp"
uglyURLs = true

[params]
  author = "abieber"

[permalinks]
  posts = "/:year/:month/:day/:slug"
